using Pkg

Pkg.update()
Pkg.instantiate()
Pkg.update()
# # Pkg.add("BenchmarkTools")
# Pkg.add("CSV")
# Pkg.add("Crayons")
# # Pkg.add("CUDA")
# Pkg.add("DataFrames")
# Pkg.add("DistributedArrays")
# # Pkg.add("FFTW")
# Pkg.add("FileIO")
# Pkg.add("ForwardDiff")
# Pkg.add("GLM")
# Pkg.add("Glob")
# Pkg.add("Images")
# Pkg.add("JSON")
# # Pkg.add("LaTeXStrings")
# # Pkg.add("Measurements")
# Pkg.add("MLBase")
# Pkg.add("OffsetArrays")
# Pkg.add("Plots")
# # Pkg.add("ProfileCanvas")
# # Pkg.add("ProgressMeter")
# # Pkg.add("Roots")
# Pkg.add("SignalDecomposition")
# # Pkg.add("StaticArrays")
# # Pkg.add("Statistics")
# # Pkg.add("Suppressor")
# Pkg.add("Symbolics")
# # Pkg.add("Lathe@v0.1.5")
# # Pkg.pin("Lathe")
# # Pkg.add("PyCall")
Pkg.resolve()
Pkg.build()
Pkg.precompile()
Pkg.gc()
